#!/usr/bin/env bash
# installs nginx on a remote server and configures it

# Install Nginx
apt-get update
apt-get install -y nginx

# Configure Nginx to listen on port 80
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
        echo 'Hello World!' > /var/www/html/index.html;
}

}" > /etc/nginx/sites-available/default

# Restart Nginx
/etc/init.d/nginx restart
