#!/usr/bin/env bash
# This program prints a string multiple times.
line=1
while (( line <= 10 ));
	do

		if (( line == 4 ))
		then
			echo "bad luck";
		elif (( line == 8))
		then
			echo "good luck";
		else
			echo "Best School";
		fi

		((line++))
done
