#!/usr/bin/env bash
# This program prints a string multiple times.
line=1

while (( line <= 20 ))
do
	case $line in
		4)
			echo "$line"
			echo "bad luck from China"
			;;
		9)
			echo "$line"
			echo "bad luck from Japan"
			;;
		17)
			echo "$line"
			echo "bad luck from Italy"
			;;
		*)
			echo $line
			;;
	esac

	((line++))
done
