#!/usr/bin/env bash
# This program prints a string multiple times.
minute=1

while (( minute <= 20 ))
do
	case $line in
		4)
			echo "$line and then bad luck from China"
			;;
		9)
			echo "$line and then bad luck from Japan"
			;;
		17)
			echo "$line and then bad luck from Italy"
			;;
		*)
			echo $line
			;;
	esac

	((line++))
done
