#!/usr/bin/env bash
# This program prints a string multiple times.
hour=0
while (( hour <= 12 ));
	do
		echo "Hour: $hour";

		minuite=1

		while (( minuite < 60 ));
		do
			echo "$minuite";
			(( minuite++))
		done

		((hour++))
done
