#!/usr/bin/env bash
# This program prints a string multiple times.

Hour=0

while (( Hour <= 12 ))
do
	echo "Hour: $Hour";

	minute=1
	while (( minute <= 59))
	do
		echo "$minute";
		((minute++))
	done

	(( Hour++ ))
done
