#!/usr/bin/env bash

# Display the content of the current directory
# in a list format, showing only the part of the name
# after the first dash.

for file in *
do
	if [[ $file != .* ]]
	then
		name_part=$(echo "$file" | cut -d'-' -f2)
		echo "$name_part"
	fi
done
